name: Staging Rollout

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install hugo
      run: |
        cd /tmp/
        wget https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.tar.gz 
        tar xf hugo_0.55.6_Linux-64bit.tar.gz
        sudo ln -s $(pwd)/hugo /usr/bin/hugo
        cd -

    - name: Build site
      run: |
        hugo
        
    - name: Rollout site
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        eval $(ssh-agent -s)
        ssh-add - <<< "${SSH_KEY}"
        rsync --exclude=/w --delete -r -e "ssh -o StrictHostKeyChecking=no -p 22" public/ web@web2.fossgis.de:/
